### ISSUE TITLE
Awesome tool! Although a little buggy

### ISSUE THREAD

**Issue by mort286f** [ranky/ArchnemesisRecipies#7]
Hi! I discovered this awesome tool this morning, and my god does it make the league mechanic much easier. Although I noticed that if you were to hover over some of the bottom "skulls" to see what theyre combined from, the site would try to expand to compensate the box display from me hovering over the skull with my mouse. Gave me a very hard time actually reading what combinations were necessary. 

![chrome_ejmB56mF6d](https://user-images.githubusercontent.com/57791299/153362290-b2654671-953c-4a37-9edb-36fc6530751e.gif)

**Comment by Seriousnes** [comment]
I'm looking into this one, sorry about that.

**Comment by mort286f** [comment]
All good. Just thought id let you know. Good luck with it.

**Comment by Seriousnes** [comment]
This has been fixed
